/***
 * THIS FILE IS AUTOMATICALLY GENERATED
 * Do not edit this file. It will be overwritten when the configure script is run.
 ***/

#include "cache.h"
#include "champsim.h"
#include "dram_controller.h"
#include "ooo_cpu.h"
#include "vmem.h"
#include "champsim_constants.h"
#include <vector>
CACHE LLC("LLC", 2048, 16, 32, 32, 32, 64, 1, 1);
std::vector<O3_CPU> ooo_cpu {  };
MEMORY_CONTROLLER DRAM("DRAM");
VirtualMemory vmem(NUM_CPUS, 8589934592, PAGE_SIZE, 5, 1);

